import { PropsFromKeys } from '@codelab/shared/interface/props'

export namespace TimePicker {
  export const propKeys = [
    'allowClear',
    'autoFocus',
    'bordered',
    'className',
    'clearText',
    'defaultValue',
    'disabled',
    'disabledHours',
    'disabledMinutes',
    'disabledSeconds',
    'format',
    'getPopupContainer',
    'hideDisabledOptions',
    'hourStep',
    'inputReadOnly',
    'minuteStep',
    'open',
    'placeholder',
    'popupClassName',
    'popupStyle',
    'secondStep',
    'suffixIcon',
    'clearIcon',
    'use12Hours',
    'renderExtraFooter',
    'value',
    'onChange',
    'onOpenChange',
  ] as const

  export const rangePickerPropKeys = [
    'allowClear',
    'autoFocus',
    'className',
    'dateRender',
    'disabled',
    'disabledDate',
    'dropdownClassName',
    'getPopupContainer',
    'locale',
    'mode',
    'open',
    'picker',
    'placeholder',
    'popupStyle',
    'size',
    'bordered',
    'suffixIcon',
    'style',
    'onOpenChange',
    'onPanelChange',
    'inputReadOnly',
    'allowEmpty',
    'dateRender',
    'defaultValue',
    'defaultPickerValue',
    'disabled',
    'disabledTime',
    'format',
    'ranges',
    'renderExtraFooter',
    'separator',
    'showTime',
    'showTime.defaultValue',
    'value',
    'onCalendarChange',
    'onChange',
    'order',
  ] as const

  export type Props = PropsFromKeys<typeof propKeys[number]>

  export type RangePickerProps = PropsFromKeys<
    typeof rangePickerPropKeys[number]
  >
}
