import { PropsFromKeys } from '@codelab/props'

export const timePickerPropKeys = [
  'allowClear',
  'autoFocus',
  'bordered',
  'className',
  'clearText',
  'defaultValue',
  'disabled',
  'disabledHours',
  'disabledMinutes',
  'disabledSeconds',
  'format',
  'getPopupContainer',
  'hideDisabledOptions',
  'hourStep',
  'inputReadOnly',
  'minuteStep',
  'open',
  'placeholder',
  'popupClassName',
  'popupStyle',
  'secondStep',
  'suffixIcon',
  'clearIcon',
  'use12Hours',
  'renderExtraFooter',
  'value',
  'onChange',
  'onOpenChange',
] as const

export const rangePickerPropKeys = [
  'allowClear',
  'autoFocus',
  'className',
  'dateRender',
  'disabled',
  'disabledDate',
  'dropdownClassName',
  'getPopupContainer',
  'locale',
  'mode',
  'open',
  'picker',
  'placeholder',
  'popupStyle',
  'size',
  'bordered',
  'suffixIcon',
  'style',
  'onOpenChange',
  'onPanelChange',
  'inputReadOnly',
  'allowEmpty',
  'dateRender',
  'defaultValue',
  'defaultPickerValue',
  'disabled',
  'disabledTime',
  'format',
  'ranges',
  'renderExtraFooter',
  'separator',
  'showTime',
  'showTime.defaultValue',
  'value',
  'onCalendarChange',
  'onChange',
  'order',
] as const

export type TimePickerProps = PropsFromKeys<typeof timePickerPropKeys[number]>

export type RangePickerProps = PropsFromKeys<typeof rangePickerPropKeys[number]>
